CREATE TABLE gage (
  hour int(11) NOT NULL,
  day int(11) NOT NULL,
  month int(11) NOT NULL,
  year int(11) NOT NULL,
  family varchar(255) NOT NULL,
  event varchar(255) NOT NULL,
  date date NOT NULL,
  count int(11) DEFAULT NULL,
  details longblob,
  PRIMARY KEY (hour,day,month,year,family,event,date),
  KEY hour (hour),
  KEY day (day),
  KEY month (month),
  KEY year (year),
  KEY event (event),
  KEY hour_event (hour,event),
  KEY day_event (day,event),
  KEY month_event (event,month),
  KEY year_event (year,event),
  KEY day_month_year_event (day,month,year,event),
  KEY day_month (day,month),
  KEY day_month_year (day,month,year),
  KEY date (date),
  KEY date_event (date,event),
  KEY event_family (family,event),
  KEY family_date (date),
  KEY family (family)
) ENGINE=InnoDB DEFAULT CHARSET=utf8